"""link sessions and refresh tokens

Revision ID: 1d8eac4bc74d
Revises: d54564b0334d
Create Date: 2026-07-01 15:37:51.895502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8eac4bc74d'
down_revision: Union[str, Sequence[str], None] = 'd54564b0334d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user_sessions', ['refresh_token_id'])
    op.create_foreign_key(None, 'user_sessions', 'refresh_tokens', ['refresh_token_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'refresh_token_id')
    # ### end Alembic commands ###
